name: Generate Snake

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # 关键权限设置

      - name: Create assets directory
        run: mkdir -p assets  # 确保目录存在

      - name: Generate Snake
        uses: platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_path: assets/github-snake.svg

      - name: Commit SVG
        run: |
          # 添加文件存在性检查
          if [ -f "assets/github-snake.svg" ]; then
            git config --global user.name github-actions
            git config --global user.email github-actions@github.com
            git add assets/github-snake.svg
            git commit -m "Update snake"
            git push
          else
            echo "SVG file not found, skipping commit"
          fi
