name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate Snake
        uses: platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # 新版参数格式
          outputs: assets/github-snake.svg  # 直接生成到根目录
          # 有效参数列表：
          # github_user_name (必需)
          # github_token (可选，默认自动生成)
          # outputs (输出文件名)
          # args (直接传递 CLI 参数)
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/github-snake.svg
          if git diff-index --quiet HEAD --; then
            echo "No changes"
          else
            git commit -m "Update snake"
            git push
          fi
